language: node_js

node_js:
  - "stable"

sudo: false

git:
  depth: 1

install:
  - yarn global add https://github.com/rispa-io/rispa-test-utils.git#feature/initial-impl

script:
  - ris-test-utils init
  - ris-test-utils run redux lint
  - ris-test-utils run redux test:coverage

cache:
  yarn: true

  directories:
      - $TRAVIS_BUILD_DIR/../rispa-project
